import type { CouchesCarteWalkZen } from './typesStyleCarte';

export const COUCHES_CARTE_WALKZEN_CLAIR: CouchesCarteWalkZen = [
  {
    id: 'standard-light-vector-background',
    type: 'background',
    paint: { 'background-color': '#F1EEE8' },
  },
  {
    id: 'standard-light-vector-water',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'water',
    minzoom: 0,
    paint: { 'fill-color': '#B8DFF2', 'fill-opacity': 0.98 },
  },
  {
    id: 'standard-light-vector-waterway',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'waterway',
    minzoom: 8,
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#86C7E8',
      'line-width': ['interpolate', ['linear'], ['zoom'], 8, 0.6, 13, 1.2, 17, 2.4, 19, 3.4],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0.5, 13, 0.72, 17, 0.9],
    },
  },
  {
    id: 'standard-light-vector-landcover',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'landcover',
    minzoom: 8,
    filter: ['in', ['get', 'class'], ['literal', ['grass', 'wood', 'scrub', 'park', 'forest']]],
    paint: {
      'fill-color': [
        'match',
        ['get', 'class'],
        'wood',
        '#8FEA78',
        'forest',
        '#8FEA78',
        'scrub',
        '#A8F08F',
        'grass',
        '#B6F59D',
        'park',
        '#84F35E',
        '#B6F59D',
      ],
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0.68, 14, 0.88, 18, 0.96],
    },
  },
  {
    id: 'standard-light-vector-landuse',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'landuse',
    minzoom: 10,
    filter: ['in', ['get', 'class'], ['literal', ['park', 'grass', 'forest', 'wood', 'cemetery', 'garden', 'recreation_ground']]],
    paint: {
      'fill-color': '#84F35E',
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 10, 0.68, 15, 0.92, 18, 0.98],
    },
  },
  {
    id: 'standard-light-vector-education-landuse',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'landuse',
    minzoom: 10,
    filter: ['in', ['get', 'class'], ['literal', ['school', 'education', 'university', 'college', 'kindergarten']]],
    paint: {
      'fill-color': '#FFF3A6',
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 10, 0.56, 14, 0.76, 18, 0.9],
    },
  },
  {
    id: 'standard-light-vector-education-outline',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'landuse',
    minzoom: 13,
    filter: ['in', ['get', 'class'], ['literal', ['school', 'education', 'university', 'college', 'kindergarten']]],
    paint: {
      'line-color': 'rgba(213,179,63,0.36)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 13, 0.4, 16, 0.8, 19, 1.2],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.34, 16, 0.56, 19, 0.72],
    },
  },
  {
    id: 'standard-light-vector-building-fill',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'building',
    minzoom: 14,
    paint: {
      'fill-color': '#D1C8BC',
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 14, 0.64, 17, 0.82, 19, 0.92],
    },
  },
  {
    id: 'standard-light-vector-building-outline',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'building',
    minzoom: 15,
    paint: {
      'line-color': 'rgba(130,110,90,0.34)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 15, 0.4, 18, 1],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0.42, 18, 0.78],
    },
  },
  {
    id: 'standard-light-vector-major-road-casing',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 10,
    filter: ['in', ['get', 'class'], ['literal', ['motorway', 'trunk', 'primary', 'secondary']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': ['match', ['get', 'class'], 'motorway', '#D94F86', 'trunk', '#D94F86', 'primary', '#D8C746', 'secondary', '#D8C746', '#D8B900'],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.8, 12, 3.2, 13, 4.8, 15, 7.4, 17, 11.8, 19, 17.2],
      'line-opacity': 0,
    },
  },
  {
    id: 'standard-light-vector-major-road-fill',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 10,
    filter: ['in', ['get', 'class'], ['literal', ['motorway', 'trunk', 'primary', 'secondary']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': ['match', ['get', 'class'], 'motorway', '#FF6FA8', 'trunk', '#FF6FA8', 'primary', '#FFF176', 'secondary', '#FFF176', '#FFF6B8'],
      'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1.4, 12, 2.7, 13, 4.2, 15, 6.5, 17, 10.5, 19, 15.6],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 10, 0.82, 15, 0.96, 18, 1],
    },
  },
  {
    id: 'standard-light-vector-road-casing',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 12,
    filter: ['in', ['get', 'class'], ['literal', ['tertiary', 'minor', 'service', 'pedestrian', 'path']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#D8D3CB',
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 3.1, 15, 6.3, 17, 10.9, 19, 16.3],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0.45, 15, 0.62, 18, 0.76],
    },
  },
  {
    id: 'standard-light-vector-road-fill',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 12,
    filter: ['in', ['get', 'class'], ['literal', ['tertiary', 'minor', 'service', 'pedestrian', 'path']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': ['match', ['get', 'class'], 'secondary', '#FFFFFF', 'tertiary', '#FFFFFF', 'minor', '#FFFFFF', 'service', '#FFFFFF', 'pedestrian', '#FCFCFC', '#FFFFFF'],
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 2.55, 15, 5.3, 17, 9.4, 19, 14.5],
      'line-opacity': 1,
    },
  },
  {
    id: 'standard-light-vector-pedestrian-paths',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 15,
    filter: ['in', ['get', 'class'], ['literal', ['pedestrian', 'path', 'service']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#9EA4A8',
      'line-width': ['interpolate', ['linear'], ['zoom'], 15, 1.15, 17, 1.7, 19, 2.35],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0.56, 18, 0.86],
      'line-dasharray': [1.4, 2.0],
    },
  },
  {
    id: 'standard-light-vector-railway-casing',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 12,
    filter: [
      'any',
      ['==', ['get', 'class'], 'rail'],
      ['==', ['get', 'class'], 'railway'],
      ['==', ['get', 'subclass'], 'rail'],
      ['==', ['get', 'subclass'], 'railway'],
      ['==', ['get', 'subclass'], 'train'],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': 'rgba(255,255,255,0.8)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1.6, 15, 2.2, 17, 3.2, 19, 4.2],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0.42, 15, 0.62, 18, 0.76],
    },
  },
  {
    id: 'standard-light-vector-railway',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 12,
    filter: [
      'any',
      ['==', ['get', 'class'], 'rail'],
      ['==', ['get', 'class'], 'railway'],
      ['==', ['get', 'subclass'], 'rail'],
      ['==', ['get', 'subclass'], 'railway'],
      ['==', ['get', 'subclass'], 'train'],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#56636B',
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 0.9, 15, 1.45, 17, 2.15, 19, 3],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0.7, 15, 0.86, 18, 0.96],
      'line-dasharray': [4, 2],
    },
  },
  {
    id: 'standard-light-vector-tram-casing',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 12,
    filter: [
      'any',
      ['==', ['get', 'subclass'], 'tram'],
      ['==', ['get', 'subclass'], 'tram_stop'],
      ['==', ['get', 'subclass'], 'light_rail'],
      ['==', ['get', 'class'], 'tram'],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#FFFFFF',
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 2.2, 15, 3.2, 17, 4.6, 19, 6.2],
      'line-opacity': 0.58,
    },
  },
  {
    id: 'standard-light-vector-tram-rail',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 12,
    filter: [
      'any',
      ['==', ['get', 'subclass'], 'tram'],
      ['==', ['get', 'subclass'], 'tram_stop'],
      ['==', ['get', 'subclass'], 'light_rail'],
      ['==', ['get', 'class'], 'tram'],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': '#6D6274',
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 15, 1.55, 17, 2.25, 19, 3.1],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0.36, 15, 0.5, 18, 0.66],
      'line-dasharray': [4, 3],
    },
  },
  {
    id: 'standard-light-vector-street-labels',
    type: 'symbol',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation_name',
    minzoom: 13,
    filter: ['in', ['get', 'class'], ['literal', ['primary', 'secondary', 'tertiary', 'minor', 'service', 'path', 'pedestrian']]],
    layout: {
      'symbol-placement': 'line',
      'text-field': ['coalesce', ['get', 'name'], ['get', 'name:latin']],
      'text-font': ['Inter Medium', 'Noto Sans Medium'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 13, 8.8, 16, 10.2, 19, 12],
      'text-letter-spacing': 0,
      'text-rotation-alignment': 'map',
      'text-pitch-alignment': 'viewport',
      'text-keep-upright': true,
      'text-max-angle': 35,
      'text-padding': 5,
    },
    paint: {
      'text-color': '#3F3933',
      'text-halo-color': 'rgba(255,255,255,0.97)',
      'text-halo-width': 2.2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.62, 16, 0.9],
    },
  },
];
