import type { CouchesCarteWalkZen } from './typesStyleCarte';

export const COUCHES_CARTE_WALKZEN_SOMBRE: CouchesCarteWalkZen = [
  {
    id: 'standard-dark-background',
    type: 'background',
    paint: { 'background-color': '#020B12' },
  },
  {
    id: 'standard-dark-green-landcover',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'landcover',
    minzoom: 8,
    filter: ['in', ['get', 'class'], ['literal', ['grass', 'wood', 'scrub', 'park', 'forest']]],
    paint: {
      'fill-color': [
        'match',
        ['get', 'class'],
        'wood',
        'rgba(20,83,45,0.5)',
        'forest',
        'rgba(20,83,45,0.5)',
        'scrub',
        'rgba(22,101,52,0.42)',
        'grass',
        'rgba(34,197,94,0.28)',
        'park',
        'rgba(34,197,94,0.32)',
        'rgba(22,101,52,0.32)',
      ],
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0.28, 13, 0.4, 16, 0.52, 19, 0.62],
    },
  },
  {
    id: 'standard-dark-green-landuse',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'landuse',
    minzoom: 10,
    filter: ['in', ['get', 'class'], ['literal', ['park', 'grass', 'forest', 'wood', 'cemetery', 'pitch', 'garden', 'recreation_ground']]],
    paint: {
      'fill-color': [
        'match',
        ['get', 'class'],
        'cemetery',
        'rgba(22,101,52,0.28)',
        'pitch',
        'rgba(34,197,94,0.22)',
        'garden',
        'rgba(34,197,94,0.3)',
        'park',
        'rgba(34,197,94,0.34)',
        'grass',
        'rgba(34,197,94,0.28)',
        'forest',
        'rgba(20,83,45,0.48)',
        'wood',
        'rgba(20,83,45,0.48)',
        'rgba(22,101,52,0.3)',
      ],
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 10, 0.28, 14, 0.44, 17, 0.58, 19, 0.68],
    },
  },
  {
    id: 'standard-dark-green-park',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'park',
    minzoom: 10,
    paint: {
      'fill-color': 'rgba(34,197,94,0.34)',
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 10, 0.32, 14, 0.5, 17, 0.66, 19, 0.76],
    },
  },
  {
    id: 'standard-dark-classic-building-fill',
    type: 'fill',
    source: 'walkzen-dark-vector',
    'source-layer': 'building',
    minzoom: 13,
    paint: {
      'fill-color': '#132B3A',
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.22, 15, 0.34, 17, 0.48, 19, 0.6],
    },
  },
  {
    id: 'standard-dark-classic-building-outline',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'building',
    minzoom: 14,
    paint: {
      'line-color': 'rgba(186,239,255,0.32)',
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 14, 0.34, 16, 0.5, 18, 0.66],
      'line-width': ['interpolate', ['linear'], ['zoom'], 14, 0.35, 16, 0.7, 18, 1.05],
    },
  },
  {
    id: 'standard-dark-road-casing',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 12,
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': 'rgba(2,11,18,0.96)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1.4, 15, 2.8, 17, 5, 19, 8.5],
      'line-opacity': 0,
    },
  },
  {
    id: 'standard-dark-safe-street-halo',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 15,
    filter: ['in', ['get', 'class'], ['literal', ['tertiary', 'minor', 'service', 'pedestrian', 'path']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': 'rgba(34,197,94,0.55)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 15, 2.4, 17, 3.6, 19, 5],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0.08, 17, 0.13, 19, 0.18],
      'line-blur': 2.2,
    },
  },
  {
    id: 'standard-dark-road-centerline',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 15,
    filter: ['in', ['get', 'class'], ['literal', ['motorway', 'trunk', 'primary', 'secondary', 'tertiary', 'minor', 'service', 'pedestrian']]],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': [
        'match',
        ['get', 'class'],
        'motorway',
        '#D0D7DD',
        'trunk',
        '#D5DBE0',
        'primary',
        '#D9DEE2',
        'secondary',
        '#E3E7EA',
        'tertiary',
        '#ECEFF1',
        'minor',
        '#F5F6F7',
        'service',
        'rgba(255,255,255,0.22)',
        'pedestrian',
        'rgba(255,255,255,0.2)',
        'rgba(255,255,255,0.26)',
      ],
      'line-width': [
        'interpolate',
        ['linear'],
        ['zoom'],
        15,
        ['match', ['get', 'class'], 'motorway', 0.95, 'trunk', 0.9, 'primary', 0.78, 'secondary', 0.68, 'tertiary', 0.6, 0.5],
        17,
        ['match', ['get', 'class'], 'motorway', 1.45, 'trunk', 1.35, 'primary', 1.15, 'secondary', 1, 'tertiary', 0.9, 0.72],
        19,
        ['match', ['get', 'class'], 'motorway', 2.1, 'trunk', 1.95, 'primary', 1.65, 'secondary', 1.45, 'tertiary', 1.25, 0.95],
      ],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0.48, 17, 0.72, 19, 0.86],
      'line-dasharray': ['match', ['get', 'class'], 'motorway', ['literal', [2.8, 2.2]], 'trunk', ['literal', [2.6, 2.2]], 'primary', ['literal', [2.4, 2.3]], ['literal', [1.6, 2.8]]],
    },
  },
  {
    id: 'standard-dark-bridge-underlay',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 13,
    filter: ['any', ['==', ['get', 'brunnel'], 'bridge'], ['==', ['get', 'bridge'], 'yes'], ['==', ['get', 'bridge'], 1], ['==', ['get', 'structure'], 'bridge']],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': 'rgba(2,11,18,0.92)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 13, 4.5, 15, 6.4, 17, 8.8, 19, 11.5],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.28, 17, 0.55, 19, 0.7],
      'line-blur': 0.8,
    },
  },
  {
    id: 'standard-dark-bridge-highlight',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 13,
    filter: ['any', ['==', ['get', 'brunnel'], 'bridge'], ['==', ['get', 'bridge'], 'yes'], ['==', ['get', 'bridge'], 1], ['==', ['get', 'structure'], 'bridge']],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': 'rgba(103,232,249,0.72)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 13, 2.6, 15, 4.1, 17, 6, 19, 8.6],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.26, 15, 0.44, 17, 0.62, 19, 0.78],
      'line-blur': 1.4,
    },
  },
  {
    id: 'standard-dark-railway',
    type: 'line',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation',
    minzoom: 13,
    filter: [
      'any',
      ['==', ['get', 'class'], 'rail'],
      ['==', ['get', 'class'], 'railway'],
      ['==', ['get', 'subclass'], 'rail'],
      ['==', ['get', 'subclass'], 'railway'],
      ['==', ['get', 'subclass'], 'train'],
    ],
    layout: { 'line-cap': 'round', 'line-join': 'round' },
    paint: {
      'line-color': 'rgba(120,140,155,0.55)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 13, 0.8, 15, 1.2, 17, 1.8, 19, 2.4],
      'line-opacity': 0.7,
      'line-dasharray': [3, 2],
    },
  },
  {
    id: 'standard-dark-street-labels-main',
    type: 'symbol',
    source: 'walkzen-dark-vector',
    'source-layer': 'transportation_name',
    minzoom: 12,
    filter: ['in', ['get', 'class'], ['literal', ['primary', 'secondary', 'tertiary', 'trunk', 'minor', 'service', 'track', 'path', 'pedestrian']]],
    layout: {
      'symbol-placement': 'line',
      'text-field': ['coalesce', ['get', 'name'], ['get', 'name:latin']],
      'text-font': ['Inter Medium', 'Noto Sans Medium'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 12, 11, 14, 13, 17, 14],
      'text-letter-spacing': 0,
      'text-rotation-alignment': 'map',
      'text-pitch-alignment': 'viewport',
      'text-keep-upright': true,
      'text-max-angle': 35,
      'text-padding': 5,
    },
    paint: {
      'text-color': '#E2E8F0',
      'text-halo-color': 'rgba(0,0,0,0.85)',
      'text-halo-width': 2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0.72, 14, 0.94],
    },
  },
  {
    id: 'standard-dark-commerce-dots',
    type: 'circle',
    source: 'walkzen-dark-vector',
    'source-layer': 'poi',
    minzoom: 16,
    filter: [
      'all',
      ['any', ['has', 'name'], ['has', 'name:latin']],
      ['any', ['in', ['get', 'class'], ['literal', ['shop', 'food', 'drink']]], ['in', ['get', 'subclass'], ['literal', ['bakery', 'bar', 'butcher', 'cafe', 'chemist', 'clothes', 'convenience', 'fast_food', 'florist', 'greengrocer', 'hairdresser', 'restaurant', 'shop', 'supermarket']]]],
    ],
    paint: {
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 16, 2.2, 18, 3.2, 20, 4],
      'circle-color': '#22D3EE',
      'circle-opacity': ['interpolate', ['linear'], ['zoom'], 16, 0.34, 18, 0.58],
      'circle-stroke-color': 'rgba(2,11,18,0.86)',
      'circle-stroke-width': 1.2,
    },
  },
  {
    id: 'standard-dark-administration-dots',
    type: 'circle',
    source: 'walkzen-dark-vector',
    'source-layer': 'poi',
    minzoom: 15,
    filter: [
      'all',
      ['any', ['has', 'name'], ['has', 'name:latin']],
      ['any', ['in', ['get', 'class'], ['literal', ['government', 'office']]], ['in', ['get', 'subclass'], ['literal', ['courthouse', 'embassy', 'fire_station', 'government', 'post', 'post_office', 'public_building', 'social_facility', 'town_hall']]]],
    ],
    paint: {
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 15, 2.4, 17, 3.4, 19, 4.4],
      'circle-color': '#A5B4FC',
      'circle-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0.42, 17, 0.64],
      'circle-stroke-color': 'rgba(2,11,18,0.88)',
      'circle-stroke-width': 1.3,
    },
  },
  {
    id: 'standard-dark-transit-dots',
    type: 'circle',
    source: 'walkzen-dark-vector',
    'source-layer': 'poi',
    minzoom: 14,
    filter: [
      'all',
      ['any', ['has', 'name'], ['has', 'name:latin']],
      ['any', ['in', ['get', 'class'], ['literal', ['railway', 'transport']]], ['in', ['get', 'subclass'], ['literal', ['bus', 'bus_stop', 'ferry_terminal', 'halt', 'light_rail', 'metro', 'railway', 'station', 'subway', 'tram', 'tram_stop', 'train', 'transport']]]],
    ],
    paint: {
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 14, 2.6, 16, 3.6, 18, 4.8],
      'circle-color': '#38BDF8',
      'circle-opacity': ['interpolate', ['linear'], ['zoom'], 14, 0.44, 16, 0.68],
      'circle-stroke-color': 'rgba(2,11,18,0.9)',
      'circle-stroke-width': 1.4,
    },
  },
  {
    id: 'standard-dark-health-dots',
    type: 'circle',
    source: 'walkzen-dark-vector',
    'source-layer': 'poi',
    minzoom: 15,
    filter: ['all', ['any', ['has', 'name'], ['has', 'name:latin']], ['in', ['get', 'subclass'], ['literal', ['chemist', 'clinic', 'doctors', 'hospital', 'pharmacy']]]],
    paint: {
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 15, 3.2, 17, 4.8, 19, 6],
      'circle-color': '#F43F5E',
      'circle-opacity': 0.88,
      'circle-stroke-color': '#F8FAFC',
      'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 15, 1, 18, 1.6],
    },
  },
  {
    id: 'standard-dark-poi-labels',
    type: 'symbol',
    source: 'walkzen-dark-vector',
    'source-layer': 'poi',
    minzoom: 17,
    filter: ['all', ['any', ['has', 'name'], ['has', 'name:latin']], ['in', ['get', 'class'], ['literal', ['shop', 'food', 'drink', 'railway', 'transport', 'government', 'office']]]],
    layout: {
      'text-anchor': 'top',
      'text-field': ['coalesce', ['get', 'name'], ['get', 'name:latin']],
      'text-font': ['Inter Medium', 'Noto Sans Medium'],
      'text-max-width': 9,
      'text-offset': [0, 0.7],
      'text-padding': 4,
      'text-size': ['interpolate', ['linear'], ['zoom'], 17, 10, 19, 11.5],
    },
    paint: {
      'text-color': '#BAEFFF',
      'text-halo-color': 'rgba(0,0,0,0.86)',
      'text-halo-width': 1.6,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 17, 0.68, 18, 0.88],
    },
  },
];
