import { StyleSheet } from 'react-native';

export const stylesCarte = StyleSheet.create({
  carte: {
    flex: 1,
  },
  ancreMarqueurUtilisateur: {
    alignItems: 'center',
    height: 66,
    justifyContent: 'center',
    shadowColor: '#1e90ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.62,
    shadowRadius: 18,
    width: 66,
  },
  imageMarqueurUtilisateur: {
    height: 66,
    resizeMode: 'contain',
    width: 66,
  },
  marqueurDepart: {
    backgroundColor: '#13b6d8',
    borderColor: '#ffffff',
    borderRadius: 11,
    borderWidth: 3,
    height: 22,
    shadowColor: '#13b6d8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    width: 22,
  },
  marqueurArriveeRacine: {
    height: 78,
    width: 78,
  },
  marqueurArriveeContenu: {
    height: 78,
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.34,
    shadowRadius: 18,
    width: 78,
  },
  hampeArrivee: {
    backgroundColor: '#CBD5E1',
    borderColor: 'rgba(7,24,39,0.72)',
    borderRadius: 999,
    borderWidth: 2,
    height: 54,
    left: 21,
    position: 'absolute',
    top: 8,
    width: 4,
  },
  drapeauArrivee: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(7,24,39,0.9)',
    borderRadius: 6,
    borderTopLeftRadius: 3,
    borderBottomLeftRadius: 3,
    borderWidth: 2,
    height: 25,
    left: 25,
    overflow: 'hidden',
    position: 'absolute',
    shadowColor: '#17D4FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    top: 8,
    width: 36,
  },
  ligneDrapeauArrivee: {
    flexDirection: 'row',
    flex: 1,
  },
  carreDrapeauClair: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  carreDrapeauFonce: {
    backgroundColor: '#111827',
    flex: 1,
  },
  etiquetteArrivee: {
    backgroundColor: 'rgba(7,24,39,0.95)',
    borderColor: 'rgba(255,255,255,0.55)',
    borderRadius: 999,
    borderWidth: 1,
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    left: 2,
    lineHeight: 14,
    paddingHorizontal: 8,
    paddingVertical: 3,
    position: 'absolute',
    top: 54,
  },
});
